// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KoiAuction.Repositories.Models;

public partial class Bid
{
    public int Id { get; set; }

    public int AuctionsId { get; set; }

    public int UserId { get; set; }

    public decimal? Amount { get; set; }

    public bool? IsWin { get; set; }

    public DateTime? CreateDate { get; set; }

    public DateTime? UpdateDate { get; set; }

    public string BidDescription { get; set; }

    public DateTime? BidTime { get; set; }

    public string Currency { get; set; }

    public string Status { get; set; }

    public virtual Auction Auctions { get; set; }

    public virtual User User { get; set; }
}