// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KoiAuction.Repositories.Models;

public partial class GroupKoi
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int FarmId { get; set; }

    public string Description { get; set; }

    public string Status { get; set; }

    public virtual ICollection<Auction> Auctions { get; set; } = new List<Auction>();

    public virtual KoiFarm Farm { get; set; }

    public virtual ICollection<Image> Images { get; set; } = new List<Image>();

    public virtual ICollection<KoiFish> KoiFishes { get; set; } = new List<KoiFish>();

    public virtual ICollection<Transaction> Transactions { get; set; } = new List<Transaction>();
}