// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KoiAuction.Repositories.Models;

public partial class Image
{
    public int Id { get; set; }

    public int GroupKoiId { get; set; }

    public int UserId { get; set; }

    public int KoiFishId { get; set; }

    public int FarmId { get; set; }

    public int? ImageOrder { get; set; }

    public virtual KoiFarm Farm { get; set; }

    public virtual GroupKoi GroupKoi { get; set; }

    public virtual KoiFish KoiFish { get; set; }

    public virtual User User { get; set; }
}