// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KoiAuction.Repositories.Models;

public partial class KoiFish
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int GroupKoiId { get; set; }

    public int FarmId { get; set; }

    public string Quantity { get; set; }

    public string Description { get; set; }

    public string Status { get; set; }

    public int? Age { get; set; }

    public DateTime? CreateDate { get; set; }

    public DateTime? UpdateDate { get; set; }

    public string Gender { get; set; }

    public virtual KoiFarm Farm { get; set; }

    public virtual GroupKoi GroupKoi { get; set; }

    public virtual ICollection<Image> Images { get; set; } = new List<Image>();
}