// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KoiAuction.Repositories.Models;

public partial class Transaction
{
    public int Id { get; set; }

    public int GroupKoiId { get; set; }

    public int AuctionsId { get; set; }

    public int FarmId { get; set; }

    public int UserId { get; set; }

    public string TransactionType { get; set; }

    public DateTime? TransactionDate { get; set; }

    public decimal? Amount { get; set; }

    public string Note { get; set; }

    public string Status { get; set; }

    public virtual Auction Auctions { get; set; }

    public virtual KoiFarm Farm { get; set; }

    public virtual GroupKoi GroupKoi { get; set; }

    public virtual User User { get; set; }
}