// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KoiAuction.Repositories.Models;

public partial class User
{
    public int Id { get; set; }

    public string Username { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public string Address { get; set; }

    public string Role { get; set; }

    public string Fullname { get; set; }

    public string Phone { get; set; }

    public DateTime? CreateDate { get; set; }

    public string Status { get; set; }

    public virtual ICollection<Auction> Auctions { get; set; } = new List<Auction>();

    public virtual ICollection<Bid> Bids { get; set; } = new List<Bid>();

    public virtual ICollection<Image> Images { get; set; } = new List<Image>();

    public virtual ICollection<Transaction> Transactions { get; set; } = new List<Transaction>();
}